# Autoriser les connexions anonymes (pas besoin de mot de passe pour les tests du Pico W)
allow_anonymous true

# 1. Ecouteur standard MQTT (pour le Raspberry Pi Pico W)
listener 1883
protocol mqtt

# 2. Ecouter WebSockets (pour l'application Web/Dashboard)
listener 9001
protocol web

# Paramètres de persistance (pour garder les messages en mémoire si besoin)
persistence true
persistence_location /mosquitto/data/

# Fichiers de logs
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout