events {
    worker_connections 1024;
}

http {
    # Redirection automatique du HTTP vers le HTTPS (Exigence de sécurité )
    server {
        listen 80;
        server_name localhost; # TODO: À remplacer par le futur domaine si nécessaire
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        # Chemins vers les certificats (à placer dans le dossier ./certs)
        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        # Optimisations SSL standards
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # 1. Proxy vers l'Application Web (le backend Node/SQLite)
        location / {
            proxy_pass http://web-backend:3000; # Nom du service dans le docker-compose
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 2. Proxy pour les WebSockets MQTT (utile pour le dashboard en temps réel)
        location /mqtt {
            proxy_pass http://mqtt-broker:9001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}