services:
  server:
    image: ${DOCKERHUB_USERNAME}/projet-server:latest
    network_mode: host
    volumes:
      - /opt/projet/database.sqlite:/app/database.sqlite
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  client:
    image: ${DOCKERHUB_USERNAME}/projet-client:latest
    network_mode: host
    restart: unless-stopped
    depends_on:
      - server
