# 1. Source de temps (On utilise les serveurs publics belges)
pool 0.be.pool.ntp.org iburst
pool 1.be.pool.ntp.org iburst
pool 2.be.pool.ntp.org iburst

# 2. Autoriser notre reseau interne a venir nous demander l'heure
# On autorise tout le grand reseau 10.1.x.x (VLAN IT, PROD, R&D...)
allow 10.1.0.0/16

# 3. Synchronisation materielle
makestep 1 3
rtcsync
