# 1. Interdire la connexion directe en Root
PermitRootLogin no 

# 2. Restreindre l'acces a un groupe ou un utilisateur precis
# (Il faudra creer cet utilisateur 'admin_it' plus tard)
AllowUsers admin_it

# 3. Limiter le temps pour taper le mot de passe (en secondes)
LoginGraceTime 30

# 4. Deconnecter les sessions inactives apres 5 minutes (300 sec)
ClientAliveInterval 300
ClientAliveCountMax 0

# (Optionel mais possible) Desactiver les mots de passe et forcer l'utilisation de cles cryptographiques :
# PasswordAuthentication no
