version: '3.8'

services:
  # 1. Rverse Proxy (Nginx) - Gère le trafic entrant et le HTTPS
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443" # Pour le HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro # Pour les certificats SSL
    depends_on:
      - web-backend
    networks:
      - iot_network

  # 2. Broker MQTT (Mosquitto) - Pour l'électronique
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - "1883:1883" # Port MQTT standard
      - "9001:9001" # Port WebSockets (utile pour le frontend Web)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - iot_network

  # 3. Backend Web (L'API dévelopée par notre équipe)
  web-backend:
    build: ./backend # Pointe vers le dossier contenatn le Dockerfile du Dev Web
    container_name: node_backend
    environment:
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883
      # TODO: Ajouter les variables spécifique aux backend si nécessaire ici
    volumes:
      # ! On monte un dossier local "./data" dans le conteneur pour que le fichier SQLite (ex: database.sqlite) ne soit pas supprimé
      - ./data:/usr/src/app/data
    depends_on:
      - db
      - mqtt-broker
    networks:
      - iot_network

# Déclaration des réseaux virtuels
networks:
  iot_network:
    driver: bridge
