events {
    worker_connections 1024;
}

http {
    # --- CONFIGURATION REAL IP (Vital pour Fail2Ban) ---
    # Ces lignes disent à Nginx: "Fais confiance au proxy de l'école et lis la vraie IP du client"
    set_real_ip_from  193.190.0.0/16; # Sous-réseau de l'EPHEC (Proxy)
    set_real_ip_from  10.100.0.0/16;  #Réseau WAN (Routeur)
    real_ip_header    X-Forwarded-For;
    real_ip_recursive on;

    server {
        # On n'écoute QUE sur le port 80, le proxy de l'école fait le reste
        listen 80;
        server_name grp-b.ephec-ti.be;

        # 1. Proxy vers l'Application Web (le backend Node/SQLite)
        location / {
            proxy_pass http://web-backend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # On force HTTPS ici pour que l'app (Node) sache que le client original est en HTTPS
            proxy_set_header X-Forwarded-Proto https;
        }

        # 2. Proxy pour les WebSockets MQTT
        location /mqtt {
            proxy_pass http://mqtt-broker:9001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}