# 1. Activer la reception des logs en UDP 
module(load="imudp")
input(type="imudp" port="514")

# 2. Activer la reception des logs en TCP
module(load="imtcp")
input(type="imtcp" port="514")

# 3. Creation d'une regle de tri 
# Cela creer automatiquement un dossier par nom de machine et un fichier par application (ex: /var/log/remote/ns-01/sshd.log)
$template RemoteLogs,"/var/log/remote/%HOSTNAME%/%PROGRAMNAME%.log"

# 4. Appliquer la regle a TOUS les logs qui arrivent par le reseau 
*.* ?RemoteLogs

# 5. Arreter le traitement ici pour les logs reseau
& stop
